In [1]:
import numpy as np 
import pandas as pd

df = pd.read_table('smalldata.txt')
print(df)

     a    b    c
0  0.1 -0.1  0.5
1  0.2 -0.2  0.4
2  0.3 -0.3  0.3
3  0.4 -0.4  0.2
4  0.5 -0.5  0.1


In [2]:
df.iloc[0,0] = np.nan 
X = df.values
print(X)

[[ nan -0.1  0.5]
 [ 0.2 -0.2  0.4]
 [ 0.3 -0.3  0.3]
 [ 0.4 -0.4  0.2]
 [ 0.5 -0.5  0.1]]


In [3]:

print(np.isnan(X))

[[ True False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]


In [4]:
print(X[np.isnan(X)])

[nan]


In [5]:
X[np.isnan(X)] = 0
print(X)

[[ 0.  -0.1  0.5]
 [ 0.2 -0.2  0.4]
 [ 0.3 -0.3  0.3]
 [ 0.4 -0.4  0.2]
 [ 0.5 -0.5  0.1]]


In [6]:
print(np.any(np.isnan(X)))

False


In [7]:
df = pd.read_table('smalldata.txt')
df.iloc[0,0] = np.nan
print(df)

     a    b    c
0  NaN -0.1  0.5
1  0.2 -0.2  0.4
2  0.3 -0.3  0.3
3  0.4 -0.4  0.2
4  0.5 -0.5  0.1


In [8]:
print(np.isnan(df))

       a      b      c
0   True  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False


In [9]:
print(df[np.isnan(df)])

    a   b   c
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN
3 NaN NaN NaN
4 NaN NaN NaN


In [10]:
print(np.any(np.isnan(df)))

True


In [11]:
df = pd.DataFrame(dict(Cat=[np.nan, 'NA', 'NaN', None],
                       Num=[np.nan, 0.5,0.5,0.5], Clean=[1,2,3,4]))
print(df)

    Cat  Num  Clean
0   NaN  NaN      1
1    NA  0.5      2
2   NaN  0.5      3
3  None  0.5      4


In [12]:
print(np.isnan(df))

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [13]:
print(df.isna())

     Cat    Num  Clean
0   True   True  False
1  False  False  False
2  False  False  False
3   True  False  False


In [15]:
print(np.sum(df['Num'].values))

nan


In [16]:
print(df['Num'].sum())

1.5


In [17]:
print(df['Num'][0] + df['Num'][1])

nan


In [18]:
print(df.dropna(axis = 0))

   Cat  Num  Clean
1   NA  0.5      2
2  NaN  0.5      3


In [19]:
print(df.dropna(axis = 1))

   Clean
0      1
1      2
2      3
3      4
